/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.crudAluno.view;

/**
 *
 * @author italo
 */
public class jfmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form jfmMenuPrincipal
     */
    public jfmMenuPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fmbMenuPrincipal = new javax.swing.JMenuBar();
        jmmArquivo = new javax.swing.JMenu();
        jmiSair = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiPerfil = new javax.swing.JMenuItem();
        jmmCadastros = new javax.swing.JMenu();
        jmiAluno = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmiProfessor = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmiTurma = new javax.swing.JMenuItem();
        jmmMovimentacoes = new javax.swing.JMenu();
        jmiAtribuirAluno = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmiAtribuirProfessor = new javax.swing.JMenuItem();
        jmmRelatorios = new javax.swing.JMenu();
        jmiRelatorioAluno = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jmiRelatorioProfessor = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jmiRelatorioTurma = new javax.swing.JMenuItem();
        jmmAjuda = new javax.swing.JMenu();
        jmiAjudaSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmmArquivo.setText("Arquivo");

        jmiSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jmiSair.setText("Sair...");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jmmArquivo.add(jmiSair);
        jmmArquivo.add(jSeparator1);

        jmiPerfil.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jmiPerfil.setText("Perfil...");
        jmmArquivo.add(jmiPerfil);

        fmbMenuPrincipal.add(jmmArquivo);

        jmmCadastros.setText("Cadastros");

        jmiAluno.setText("Aluno(a)");
        jmiAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAlunoActionPerformed(evt);
            }
        });
        jmmCadastros.add(jmiAluno);
        jmmCadastros.add(jSeparator2);

        jmiProfessor.setText("Professor(a)");
        jmiProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProfessorActionPerformed(evt);
            }
        });
        jmmCadastros.add(jmiProfessor);
        jmmCadastros.add(jSeparator3);

        jmiTurma.setText("Turma");
        jmmCadastros.add(jmiTurma);

        fmbMenuPrincipal.add(jmmCadastros);

        jmmMovimentacoes.setText("Movimentações");

        jmiAtribuirAluno.setText("Atribuir aluno(a) à turma");
        jmmMovimentacoes.add(jmiAtribuirAluno);
        jmmMovimentacoes.add(jSeparator4);

        jmiAtribuirProfessor.setText("Atribuir professor(a) à turma");
        jmmMovimentacoes.add(jmiAtribuirProfessor);

        fmbMenuPrincipal.add(jmmMovimentacoes);

        jmmRelatorios.setText("Relatórios");

        jmiRelatorioAluno.setText("Relação de alunos(as)");
        jmmRelatorios.add(jmiRelatorioAluno);
        jmmRelatorios.add(jSeparator5);

        jmiRelatorioProfessor.setText("Relaçoes de professores(as)");
        jmmRelatorios.add(jmiRelatorioProfessor);
        jmmRelatorios.add(jSeparator6);

        jmiRelatorioTurma.setText("Relações de turmas");
        jmmRelatorios.add(jmiRelatorioTurma);

        fmbMenuPrincipal.add(jmmRelatorios);

        jmmAjuda.setText("Ajuda");

        jmiAjudaSistema.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jmiAjudaSistema.setText("Sobre o sistema");
        jmmAjuda.add(jmiAjudaSistema);

        fmbMenuPrincipal.add(jmmAjuda);

        setJMenuBar(fmbMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        dispose();
    }//GEN-LAST:event_jmiSairActionPerformed

    private void jmiAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAlunoActionPerformed
       jfmAluno aluno = new jfmAluno();
       aluno.show();
    }//GEN-LAST:event_jmiAlunoActionPerformed

    private void jmiProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProfessorActionPerformed
        jfmProfessor professor = new jfmProfessor();
        professor.show();
    }//GEN-LAST:event_jmiProfessorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar fmbMenuPrincipal;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JMenuItem jmiAjudaSistema;
    private javax.swing.JMenuItem jmiAluno;
    private javax.swing.JMenuItem jmiAtribuirAluno;
    private javax.swing.JMenuItem jmiAtribuirProfessor;
    private javax.swing.JMenuItem jmiPerfil;
    private javax.swing.JMenuItem jmiProfessor;
    private javax.swing.JMenuItem jmiRelatorioAluno;
    private javax.swing.JMenuItem jmiRelatorioProfessor;
    private javax.swing.JMenuItem jmiRelatorioTurma;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JMenuItem jmiTurma;
    private javax.swing.JMenu jmmAjuda;
    private javax.swing.JMenu jmmArquivo;
    private javax.swing.JMenu jmmCadastros;
    private javax.swing.JMenu jmmMovimentacoes;
    private javax.swing.JMenu jmmRelatorios;
    // End of variables declaration//GEN-END:variables
}
